The purpose of this code is to create the four subsets of the data.
They are as follows:
    1) Before Surgery
    2) Immediately Before Surgery
    3) Immediately after Surgery
    4) Post Surgery

Additionally, we have the outcome variable which is the target variable (there are a couple that we have but we will use Failure for now)

In [766]:
#Imports:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import re

In [767]:
#Load the dictionary
dictionary = pd.read_csv("/Users/preciousajilore/Documents/GitHub/torchmtlr/data/featuredictionary_new.csv")

dictionary.columns = [col.strip() for col in dictionary.columns]

In [768]:
dictionary.columns

Index(['FEATURE DICTIONARY', 'abbreviated name', 'full name',
       'feature category', 'one-hot/multi-coding', 'Unnamed: 5'],
      dtype='object')

In [769]:
#Get a list of features considered as "before surgery"
before_surgery = dictionary.loc[dictionary['feature category'].str.strip().str.lower() == 'before surgery', 'abbreviated name'].tolist()

In [770]:
print(before_surgery)

['stxlocation', 'distal', 'penile', 'StxEtiology', 'StxLength', '# Strictures', 'charlsons', 'Cormorbidity', 'Diabetes', 'COPD', 'Smoker', 'BMI35+', 'BMI exact', 'prevprocedure', '#prevprocedures', 'cysto', 'open', 'OR date', 'urine']

In [771]:
#Get a list of features considered to be "immediately before surgery"
imm_bf_surgery = dictionary.loc[dictionary['feature category'].str.strip().str.lower() == 'immediately before surgery', 'abbreviated name'].tolist()

print(imm_bf_surgery)

['Abx', 'erectilepre', 'uti']

In [772]:
#Get a list of features considered to be "immediately after surgery"
imm_aft_surgery = dictionary.loc[dictionary['feature category'].str.strip().str.lower() == 'immediately after surgery',"abbreviated name"].tolist()

print(imm_aft_surgery)

['LOS (days)', 'spc', 'tissue', 'transection', 'Urethroplasty', 'cath removal', 'cath days']

In [773]:
#get list of features considered to be "post-surgery"
post_surgery = dictionary.loc[dictionary['feature category'].str.strip().str.lower() == 'post surgery',"abbreviated name"].tolist()

print(post_surgery)

['fu', 'failure date', 'datetofailureorfollowup', 'complication', 'clavian II+', 'claviangrade', 'earlycomps', 'signifcomp', 'minorcomp', 'ER visits', 'foley', 'SP complication', 'erectilepost', 'pain', 'chordee', 'pvd', 'donorsite', 'UTI post', 'UTI recurring', 'LUTS', 'persisting LUTS', 'Incontinence', 'Stricture ', 'Stricture intervention']

In [774]:
#get list for target variables
outcome_vars = dictionary.loc[dictionary['feature category'].str.strip().str.lower() == 'outcome to predict',"abbreviated name"].tolist()

print(outcome_vars)

['failure', 'patent', 'satisfaction']

In [775]:
before_surgery = [f.lower().strip().replace(" ","") for f in before_surgery]
imm_bf_surgery = [f.lower().strip().replace(" ","") for f in imm_bf_surgery]
imm_aft_surgery = [f.lower().strip().replace(" ", "") for f in imm_aft_surgery]
post_surgery = [f.lower().strip().replace(" ","") for f in post_surgery]

In [776]:
print(imm_aft_surgery)

['los(days)', 'spc', 'tissue', 'transection', 'urethroplasty', 'cathremoval', 'cathdays']

In [777]:
excelSheet = pd.ExcelFile('/Users/preciousajilore/Documents/GitHub/torchmtlr/notebooks/first_analysis.xlsx')
print(excelSheet.sheet_names)

['Sheet1']

In [778]:
df = pd.read_excel(
    excelSheet,
    sheet_name= 'Sheet1',
    engine = 'openpyxl'
)

In [779]:
df.shape

(1987, 63)

In [780]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ","")

In [781]:
df.columns

Index(['uahid', 'dob(yyyy-mm-dd)', 'dateofsurgery', 'monthsurg',
       'age(attimeofsurgery)', 'age:<50=0;>=50=1', 'stxlocation', 'distal',
       'penile', 'stxetiology', 'stxlength', '#strictures', 'charlsons',
       'cormorbidity', 'diabetes', 'copd', 'smoker', 'bmi35+', 'bmiexact',
       'prevprocedure', '#prevprocedures', 'cysto', 'open', 'ordate', 'urine',
       'abx', 'erectilepre', 'uti', 'los(days)', 'spc', 'tissue',
       'transection', 'urethroplasty', 'cathremoval', 'cathdays', 'failure',
       'patent', 'fu', 'failuredate', 'datetofailureorfollowup',
       'complication', 'clavianii+', 'claviangrade', 'earlycomps',
       'signifcomp', 'minorcomp', 'ervisits', 'foley', 'spcomplication',
       'erectilepost', 'pain', 'chordee', 'pvd', 'donorsite', 'utipost',
       'utirecurring', 'luts', 'persistingluts', 'incontinence', 'stricture',
       'strictureintervention', 'satisfaction', 'age_calc'],
      dtype='object')

In [782]:
df.head()

,uahid,dob(yyyy-mm-dd),dateofsurgery,monthsurg,age(attimeofsurgery),age:<50=0;>=50=1,stxlocation,distal,penile,stxetiology,...,donorsite,utipost,utirecurring,luts,persistingluts,incontinence,stricture,strictureintervention,satisfaction,age_calc
0,13066857,1953-04-04,2003-08-05,258.0,50.0,1,0,0,1.0,2,...,0,0,0,0,no,0,1.0,yes (DVIU every 1-2 years),NaN,50.0
1,4340204,1956-05-30,2003-08-06,258.0,47.0,0,0,0,1.0,4,...,0,0,0,0,no,0,0.0,no,yes,47.0
2,NaN,1949-05-19,2003-08-21,258.0,54.0,1,2,0,0.0,1,...,0,0,0,0,no,0,0.0,no,yes,54.0
3,15769359,1945-11-18,2003-08-28,257.0,57.0,1,0,0,1.0,4,...,0,1,0,0,no,0,0.0,no,yes,57.0
4,7129851,1928-11-07,2003-08-28,257.0,74.0,1,1,0,0.0,1,...,0,0,0,0,no,0,0.0,no,Not patient died approx 1.5 years post op from...,74.0

In [783]:
# Calculate the % of missing values in each column
missing_percent = df.isna().mean()

# Find columns to drop (over 50% missing)
cols_to_drop = missing_percent[missing_percent > 0.5].index

#print the columns that ww
# Drop them!
df = df.drop(columns=cols_to_drop)

print("Dropped columns:", list(cols_to_drop))
print("New shape:", df.shape)

Dropped columns: ['uahid', 'bmiexact', 'cathremoval', 'failuredate', 'signifcomp', 'minorcomp']
New shape: (1987, 57)

In [784]:
print(df.isna().sum().sort_values(ascending=False).head(20))

spcomplication           967
satisfaction             657
persistingluts           313
ervisits                 304
donorsite                304
incontinence             261
luts                     256
pain                     256
pvd                      254
chordee                  253
foley                    239
complication             232
stricture                230
strictureintervention    218
fu                       177
erectilepost             172
claviangrade             163
los(days)                123
ordate                    80
age:<50=0;>=50=1          78
dtype: int64

In [730]:
df['spcomplication'] = df['spcomplication'].fillna(0)

In [731]:
print(df["pain"].unique())

[0 nan 1 'n.a' 'no']

In [732]:
df["pain"] = df["pain"].replace({"no": 0, "n.a": np.nan})

/var/folders/cl/h60hyp6s1jg6rr9n0nfgvphw0000gn/T/ipykernel_4194/3064066830.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["pain"] = df["pain"].replace({"no": 0, "n.a": np.nan})

In [733]:
df['pain'] = df['pain'].fillna(df['pain'].median())

In [734]:
print(df.isna().sum().sort_values(ascending=False).head(10))

satisfaction      657
persistingluts    313
ervisits          304
donorsite         304
incontinence      261
luts              256
pvd               254
chordee           253
foley             239
complication      232
dtype: int64

In [735]:
drop_post_surg = [
    "satisfaction", "persistingluts", "ervisits", "donorsite",
    "incontinence", "luts", "pvd", "chordee", "foley",
    "complication"
]

df = df.drop(columns=drop_post_surg)

In [736]:
print("New shape:", df.shape)

New shape: (1987, 47)

In [737]:
print(df.isna().sum().sort_values(ascending=False).head(10))

stricture                230
strictureintervention    218
fu                       177
erectilepost             172
claviangrade             163
los(days)                123
ordate                    80
monthsurg                 78
age:<50=0;>=50=1          78
cormorbidity              74
dtype: int64

In [738]:
df['dateofsurgery'] = pd.to_datetime(df['dateofsurgery'])
df['datetofailureorfollowup'] = pd.to_datetime(df['datetofailureorfollowup'])
df["fu"] = pd.to_datetime(df["fu"], errors='coerce')

In [739]:
#Drop useless columns lol
df = df.drop(columns=['age(attimeofsurgery)'])

In [740]:
#Sanity check
df.columns

Index(['dob(yyyy-mm-dd)', 'dateofsurgery', 'monthsurg', 'age:<50=0;>=50=1',
       'stxlocation', 'distal', 'penile', 'stxetiology', 'stxlength',
       '#strictures', 'charlsons', 'cormorbidity', 'diabetes', 'copd',
       'smoker', 'bmi35+', 'prevprocedure', '#prevprocedures', 'cysto', 'open',
       'ordate', 'urine', 'abx', 'erectilepre', 'uti', 'los(days)', 'spc',
       'tissue', 'transection', 'urethroplasty', 'cathdays', 'failure',
       'patent', 'fu', 'datetofailureorfollowup', 'clavianii+', 'claviangrade',
       'earlycomps', 'spcomplication', 'erectilepost', 'pain', 'utipost',
       'utirecurring', 'stricture', 'strictureintervention', 'age_calc'],
      dtype='object')

In [552]:
failure_rate = df['failure'].mean() * 100
print(f"Percentage of people with failure: {failure_rate:.2f}%")

Percentage of people with failure: 9.06%

In [741]:
print("New shape:", df.shape)

New shape: (1987, 46)

Cleaning prev procedures column

In [742]:
print(df["#prevprocedures"].unique())

[3 5 0 10 2 1 4 7 6 20 12 11 nan 8 13 50 40 15 22 100 9 14
 'slef dilations' 'multiples' 'mulitple' 'Nr' 'NR' 18]

In [743]:
def clean_prevprocedure(val):
    # Convert to string and lower for comparison
    v = str(val).lower().strip()
    if v in ['multiples', 'mulitple', 'slef dilations']:
        return 5.0
    if v in ['nr', 'nan', '', 'none', 'nan   8']:
        return np.nan
    try:
        return float(v)
    except:
        return np.nan

In [744]:
df['#prevprocedures'] = df['#prevprocedures'].apply(clean_prevprocedure)

In [745]:
df = df.dropna(subset=["#prevprocedures"])

#Sanity check 
df["#prevprocedures"].isna().sum()
df["#prevprocedures"].unique()

array([  3.,   5.,   0.,  10.,   2.,   1.,   4.,   7.,   6.,  20.,  12.,
        11.,   8.,  13.,  50.,  40.,  15.,  22., 100.,   9.,  14.,  18.])

In [746]:
print(df["copd"].unique())

[0 1]

In [747]:
df["smoker"].unique()

array([2, 0, 1])

Cleaning the open column

In [748]:

def clean_open(val):
    # Convert to string and lower for comparison
    v = str(val).lower().strip()
    #print(f"Value: {v!r}")  # Print each value as it's processed

    if v in ['0', 'no', "No"]:
        return 0
    if v in ['1', 'Yes']:
        return 1
    #return np.nan

In [749]:
df["open_clean"] = df["open"].apply(clean_open).dropna()

In [750]:
df["open_clean"].unique()
df = df.dropna(subset=['open_clean'])
df["open_clean"].unique()

array([0., 1.])

In [751]:
df = df.drop(columns=["open"])

In [752]:
print(df["diabetes"].unique())

[1 0]

Cleanig the cormorbidity column

In [753]:
print(df["cormorbidity"].unique())

[ 1.  0. nan]

In [754]:
df = df.dropna(subset=['cormorbidity'])

In [755]:
print(df["cormorbidity"].unique())

[1. 0.]

In [756]:
print(df["charlsons"].unique())

[ 0  1  2  5  3  4  6  7 11]

In [757]:
print(df["#strictures"].unique())

[1 2]

Cleaning the stricture length column

In [758]:
print(df["stxlength"].unique())

[3.5 5 3 6.5 1 1.5 2 5.5 6 4 2.5 15 12 16 11 9 7 18 4.5 10 20 8 22 14 13
 19 7.5 17 21 '4.5' '6.5' '3.5' '0.5' '2.5' '4 bulbar and 2 penile' 8.5
 '10 (penobulbar) + 1,5 (bulbar)']

In [759]:
def split_lengths(val):
    if pd.isna(val):
        return (0.0, 0.0)
    s = str(val)
    # Find all numbers with optional decimal/comma
    nums = re.findall(r'[\d]+[.,]?[\d]*', s)
    nums = [n.replace(',', '.') for n in nums]  # replace comma with dot
    nums = [float(n) for n in nums]
    # If only one length, fill second column with 0.0
    if len(nums) == 1:
        return (nums[0], 0.0)
    elif len(nums) >= 2:
        return (nums[0], nums[1])
    else:
        return (0.0, 0.0)

In [760]:
#Apply it
df[['stxlength_1', 'stxlength_2']] = df['stxlength'].apply(split_lengths).apply(pd.Series)

In [761]:
#drop the stricture column
df = df.drop(columns=['stxlength'])

In [762]:
#Sanity check
df['stxlength_1'].unique()

array([ 3.5,  5. ,  3. ,  6.5,  1. ,  1.5,  2. ,  5.5,  6. ,  4. ,  2.5,
       15. , 12. , 16. , 11. ,  9. ,  7. , 18. ,  4.5, 10. , 20. ,  8. ,
       22. , 14. , 13. , 19. ,  7.5, 17. , 21. ,  0.5,  8.5])

Clean etiology column

In [763]:
print(df["stxetiology"].unique())

[2 4 1 0 5 3 6 '2,4' '6 (chlamydia treated at age 18)']

In [764]:
def clean_stxetiology(val):
    allowed = set(range(0, 7))  # Only codes 0–6
    if pd.isna(val):
        return []
    nums = re.findall(r'\d+', str(val))
    return [int(n) for n in nums if int(n) in allowed]

df['stxetiology_clean'] = df['stxetiology'].apply(clean_stxetiology)

In [576]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
# This will create columns like 'stxetiology_0', ..., 'stxetiology_6'
one_hot = pd.DataFrame(mlb.fit_transform(df['stxetiology_clean']), 
                       columns=[f"stxetiology_{cls}" for cls in mlb.classes_],
                       index=df.index)

# Join to your main DataFrame
df = pd.concat([df, one_hot], axis=1)

In [577]:
df.columns

Index(['dob(yyyy-mm-dd)', 'dateofsurgery', 'monthsurg', 'age:<50=0;>=50=1',
       'stxlocation', 'distal', 'penile', 'stxetiology', '#strictures',
       'charlsons', 'cormorbidity', 'diabetes', 'copd', 'smoker', 'bmi35+',
       'prevprocedure', '#prevprocedures', 'cysto', 'ordate', 'urine', 'abx',
       'erectilepre', 'uti', 'los(days)', 'spc', 'tissue', 'transection',
       'urethroplasty', 'cathdays', 'failure', 'patent', 'fu',
       'datetofailureorfollowup', 'clavianii+', 'claviangrade', 'earlycomps',
       'spcomplication', 'erectilepost', 'pain', 'utipost', 'utirecurring',
       'stricture', 'strictureintervention', 'age_calc', 'open_clean',
       'stxlength_1', 'stxlength_2', 'stxetiology_clean', 'stxetiology_0',
       'stxetiology_1', 'stxetiology_2', 'stxetiology_3', 'stxetiology_4',
       'stxetiology_5', 'stxetiology_6'],
      dtype='object')

In [578]:
df = df.drop(columns=['stxetiology', 'stxetiology_clean'])

In [579]:
#sanity check
df.columns

Index(['dob(yyyy-mm-dd)', 'dateofsurgery', 'monthsurg', 'age:<50=0;>=50=1',
       'stxlocation', 'distal', 'penile', '#strictures', 'charlsons',
       'cormorbidity', 'diabetes', 'copd', 'smoker', 'bmi35+', 'prevprocedure',
       '#prevprocedures', 'cysto', 'ordate', 'urine', 'abx', 'erectilepre',
       'uti', 'los(days)', 'spc', 'tissue', 'transection', 'urethroplasty',
       'cathdays', 'failure', 'patent', 'fu', 'datetofailureorfollowup',
       'clavianii+', 'claviangrade', 'earlycomps', 'spcomplication',
       'erectilepost', 'pain', 'utipost', 'utirecurring', 'stricture',
       'strictureintervention', 'age_calc', 'open_clean', 'stxlength_1',
       'stxlength_2', 'stxetiology_0', 'stxetiology_1', 'stxetiology_2',
       'stxetiology_3', 'stxetiology_4', 'stxetiology_5', 'stxetiology_6'],
      dtype='object')

Cleaning stricture location column

In [580]:
print(df["stxlocation"].unique())

[0 2 1 3 4 5 '0 and 1' '1 and 4']

In [581]:
def clean_stxlocation(val):
    allowed = set(range(0, 7))  # Only codes 0–5
    if pd.isna(val):
        return []
    nums = re.findall(r'\d+', str(val))
    return [int(n) for n in nums if int(n) in allowed]

df['stxlocation_clean'] = df['stxlocation'].apply(clean_stxlocation)

In [582]:
df.columns

Index(['dob(yyyy-mm-dd)', 'dateofsurgery', 'monthsurg', 'age:<50=0;>=50=1',
       'stxlocation', 'distal', 'penile', '#strictures', 'charlsons',
       'cormorbidity', 'diabetes', 'copd', 'smoker', 'bmi35+', 'prevprocedure',
       '#prevprocedures', 'cysto', 'ordate', 'urine', 'abx', 'erectilepre',
       'uti', 'los(days)', 'spc', 'tissue', 'transection', 'urethroplasty',
       'cathdays', 'failure', 'patent', 'fu', 'datetofailureorfollowup',
       'clavianii+', 'claviangrade', 'earlycomps', 'spcomplication',
       'erectilepost', 'pain', 'utipost', 'utirecurring', 'stricture',
       'strictureintervention', 'age_calc', 'open_clean', 'stxlength_1',
       'stxlength_2', 'stxetiology_0', 'stxetiology_1', 'stxetiology_2',
       'stxetiology_3', 'stxetiology_4', 'stxetiology_5', 'stxetiology_6',
       'stxlocation_clean'],
      dtype='object')

In [583]:
ml = MultiLabelBinarizer()
# This will create columns like 'stxetiology_0', ..., 'stxetiology_6'
onehot = pd.DataFrame(ml.fit_transform(df['stxlocation_clean']), 
                       columns=[f"stxlocation_{cls}" for cls in ml.classes_],
                       index=df.index)

# Join to your main DataFrame
df = pd.concat([df, onehot], axis=1)

In [584]:
df.columns

Index(['dob(yyyy-mm-dd)', 'dateofsurgery', 'monthsurg', 'age:<50=0;>=50=1',
       'stxlocation', 'distal', 'penile', '#strictures', 'charlsons',
       'cormorbidity', 'diabetes', 'copd', 'smoker', 'bmi35+', 'prevprocedure',
       '#prevprocedures', 'cysto', 'ordate', 'urine', 'abx', 'erectilepre',
       'uti', 'los(days)', 'spc', 'tissue', 'transection', 'urethroplasty',
       'cathdays', 'failure', 'patent', 'fu', 'datetofailureorfollowup',
       'clavianii+', 'claviangrade', 'earlycomps', 'spcomplication',
       'erectilepost', 'pain', 'utipost', 'utirecurring', 'stricture',
       'strictureintervention', 'age_calc', 'open_clean', 'stxlength_1',
       'stxlength_2', 'stxetiology_0', 'stxetiology_1', 'stxetiology_2',
       'stxetiology_3', 'stxetiology_4', 'stxetiology_5', 'stxetiology_6',
       'stxlocation_clean', 'stxlocation_0', 'stxlocation_1', 'stxlocation_2',
       'stxlocation_3', 'stxlocation_4', 'stxlocation_5'],
      dtype='object')

Cleaning the distal column

In [585]:
df[df["distal"] == 11]
df.loc[df['distal'] == 11, 'distal'] = 1

In [586]:
print(df["distal"].unique())

[0 1]

Cleaning penile column

In [587]:
print(df["penile"].unique())

[ 1.  0. nan]

In [588]:
df = df.dropna(subset="penile")

In [589]:
#sanity check
print(df["penile"].unique())

[1. 0.]

Cleaning the bmiexact

In [590]:
print(df.isnull().sum())

dob(yyyy-mm-dd)             16
dateofsurgery                0
monthsurg                    3
age:<50=0;>=50=1             3
stxlocation                  0
distal                       0
penile                       0
#strictures                  0
charlsons                    0
cormorbidity                 0
diabetes                     0
copd                         0
smoker                       0
bmi35+                       0
prevprocedure                0
#prevprocedures              0
cysto                        0
ordate                       4
urine                        0
abx                          0
erectilepre                 18
uti                          7
los(days)                  122
spc                          0
tissue                       1
transection                  0
urethroplasty                0
cathdays                    42
failure                      0
patent                       1
fu                         174
datetofailureorfollowup      0
clavianii+                   2
claviangrade                75
earlycomps                   4
spcomplication               0
erectilepost               165
pain                         0
utipost                      0
utirecurring                 0
stricture                  223
strictureintervention      213
age_calc                    16
open_clean                   0
stxlength_1                  0
stxlength_2                  0
stxetiology_0                0
stxetiology_1                0
stxetiology_2                0
stxetiology_3                0
stxetiology_4                0
stxetiology_5                0
stxetiology_6                0
stxlocation_clean            0
stxlocation_0                0
stxlocation_1                0
stxlocation_2                0
stxlocation_3                0
stxlocation_4                0
stxlocation_5                0
dtype: int64

In [591]:
mask_date = df["fu"].isna()
unknown_rows = df[mask_date]
print(unknown_rows[["fu", "failure"]])

      fu  failure
2    NaT        0
4    NaT        0
5    NaT        0
6    NaT        0
9    NaT        1
...   ..      ...
1645 NaT        0
1753 NaT        1
1789 NaT        0
1883 NaT        0
1919 NaT        0

[174 rows x 2 columns]

In [592]:
df['fu'] = pd.to_datetime(df['fu'], errors='coerce')  # If some are strings
df['fu'] = df['fu'].fillna(df['fu'].median())

In [593]:
#drop empty rows
#df = df.dropna(subset=['dateofsurgery', "fu"])
df["time_to_event"] = (df["fu"] - df["dateofsurgery"]).dt.days  #days

In [594]:
print(df.isna().sum())
df = df.dropna(subset=['failure', 'time_to_event'])

dob(yyyy-mm-dd)     16
dateofsurgery        0
monthsurg            3
age:<50=0;>=50=1     3
stxlocation          0
                    ..
stxlocation_2        0
stxlocation_3        0
stxlocation_4        0
stxlocation_5        0
time_to_event        0
Length: 61, dtype: int64

In [595]:
print(df["time_to_event"].describe())

count    1859.000000
mean      607.010758
std      1077.808227
min     -2133.000000
25%       143.500000
50%       343.000000
75%       644.500000
max      5889.000000
Name: time_to_event, dtype: float64

In [596]:
df = df[df["time_to_event"] >= 0].reset_index(drop=True)
df["time_to_event"].min()
print(df["time_to_event"].describe())

count    1672.000000
mean      749.833732
std      1036.840119
min         0.000000
25%       173.000000
50%       428.000000
75%       708.000000
max      5889.000000
Name: time_to_event, dtype: float64

In [597]:
failure_rate = df['failure'].mean() * 100
print(f"Percentage of people with failure: {failure_rate:.2f}%")

Percentage of people with failure: 9.75%

In [598]:
print(df.columns[df.isna().any()])

Index(['dob(yyyy-mm-dd)', 'monthsurg', 'age:<50=0;>=50=1', 'ordate',
       'erectilepre', 'uti', 'los(days)', 'tissue', 'cathdays', 'patent',
       'claviangrade', 'earlycomps', 'erectilepost', 'stricture',
       'strictureintervention', 'age_calc'],
      dtype='object')

Cleaning uti column

In [599]:
print(df["uti"].unique())

[0 1 nan 'unknown' '?' 'Not done']

In [600]:
df = df.dropna(subset=['uti'])

In [601]:
df["uti"] = df["uti"].replace("?",0)

In [602]:
print(df["uti"].unique())

[0 1 'unknown' 'Not done']

In [603]:
mask = df["uti"].isin(['unknown', 'Not done'])
unknown_rows = df[mask]
print(unknown_rows[["uti", "failure"]])

          uti  failure
16    unknown        0
21    unknown        0
23    unknown        0
25    unknown        0
38    unknown        0
54    unknown        0
59    unknown        1
62    unknown        0
98    unknown        0
141   unknown        0
163  Not done        0

In [604]:
df["uti"] = df["uti"].replace({'Not done': 'unknown'})
df["uti"] = df["uti"].replace({'unknown': -1})
df["uti"] = df["uti"].astype(int)

/var/folders/cl/h60hyp6s1jg6rr9n0nfgvphw0000gn/T/ipykernel_4194/2825339749.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["uti"] = df["uti"].replace({'unknown': -1})

In [605]:
print(df["uti"].unique())

[ 0  1 -1]

Cleaning up the los(days) column

In [606]:
print(df["los(days)"].unique())

[2 5 4 6 3 7 nan 31 '?' 18 1 0 '7 (O2 requirements' 11 'no record' 8 10 23]

In [607]:
df = df.dropna(subset=['los(days)'])
df["los(days)"] = df["los(days)"].replace("7 (O2 requirements",7)
df["los(days)"] = df["los(days)"].replace("?",0)

#
#[6 3 nan 4 '?' 2 5 1 '7 (O2 requirements' 10 0 23]

In [608]:
mask_los = df["los(days)"].isin(['no record'])
unknown = df[mask_los]
print(unknown[["los(days)", "failure"]])

     los(days)  failure
948  no record        0
968  no record        0

In [609]:
df = df[~mask_los]

In [610]:
print(df["los(days)"].unique())

[2 5 4 6 3 7 31 0 18 1 11 8 10 23]

In [611]:
df.columns

Index(['dob(yyyy-mm-dd)', 'dateofsurgery', 'monthsurg', 'age:<50=0;>=50=1',
       'stxlocation', 'distal', 'penile', '#strictures', 'charlsons',
       'cormorbidity', 'diabetes', 'copd', 'smoker', 'bmi35+', 'prevprocedure',
       '#prevprocedures', 'cysto', 'ordate', 'urine', 'abx', 'erectilepre',
       'uti', 'los(days)', 'spc', 'tissue', 'transection', 'urethroplasty',
       'cathdays', 'failure', 'patent', 'fu', 'datetofailureorfollowup',
       'clavianii+', 'claviangrade', 'earlycomps', 'spcomplication',
       'erectilepost', 'pain', 'utipost', 'utirecurring', 'stricture',
       'strictureintervention', 'age_calc', 'open_clean', 'stxlength_1',
       'stxlength_2', 'stxetiology_0', 'stxetiology_1', 'stxetiology_2',
       'stxetiology_3', 'stxetiology_4', 'stxetiology_5', 'stxetiology_6',
       'stxlocation_clean', 'stxlocation_0', 'stxlocation_1', 'stxlocation_2',
       'stxlocation_3', 'stxlocation_4', 'stxlocation_5', 'time_to_event'],
      dtype='object')

Cleaning the cathremoval column

Cleaning the complication column

Sanity check on progress

In [612]:
print(df.columns[df.isna().any()])

Index(['dob(yyyy-mm-dd)', 'monthsurg', 'age:<50=0;>=50=1', 'ordate',
       'erectilepre', 'tissue', 'cathdays', 'patent', 'claviangrade',
       'earlycomps', 'erectilepost', 'stricture', 'strictureintervention',
       'age_calc'],
      dtype='object')

Cleaning the claviangrade column

In [613]:
print(df["claviangrade"].unique())

[ 0.  1.  2.  3.  4. nan  5.]

In [614]:
df = df.dropna(subset=['claviangrade'])

In [615]:
print(df["claviangrade"].isna().sum())

0

Cleaning earlycomps column

In [616]:
df = df.dropna(subset=['earlycomps'])

In [617]:
print(df["earlycomps"].isna().sum())

0

In [618]:
failure_r = df['failure'].mean() * 100
print(f"Percentage of people with failure: {failure_r:.2f}%")

Percentage of people with failure: 9.72%

Cleaning the signifcomp column

In [619]:
df.columns

Index(['dob(yyyy-mm-dd)', 'dateofsurgery', 'monthsurg', 'age:<50=0;>=50=1',
       'stxlocation', 'distal', 'penile', '#strictures', 'charlsons',
       'cormorbidity', 'diabetes', 'copd', 'smoker', 'bmi35+', 'prevprocedure',
       '#prevprocedures', 'cysto', 'ordate', 'urine', 'abx', 'erectilepre',
       'uti', 'los(days)', 'spc', 'tissue', 'transection', 'urethroplasty',
       'cathdays', 'failure', 'patent', 'fu', 'datetofailureorfollowup',
       'clavianii+', 'claviangrade', 'earlycomps', 'spcomplication',
       'erectilepost', 'pain', 'utipost', 'utirecurring', 'stricture',
       'strictureintervention', 'age_calc', 'open_clean', 'stxlength_1',
       'stxlength_2', 'stxetiology_0', 'stxetiology_1', 'stxetiology_2',
       'stxetiology_3', 'stxetiology_4', 'stxetiology_5', 'stxetiology_6',
       'stxlocation_clean', 'stxlocation_0', 'stxlocation_1', 'stxlocation_2',
       'stxlocation_3', 'stxlocation_4', 'stxlocation_5', 'time_to_event'],
      dtype='object')

In [620]:
print(df.columns[df.isna().any()])

Index(['dob(yyyy-mm-dd)', 'erectilepre', 'tissue', 'cathdays', 'patent',
       'erectilepost', 'stricture', 'strictureintervention', 'age_calc'],
      dtype='object')

Cleaning spcomplication

In [621]:
print(df["spcomplication"].unique())

['no' 0 'No'
 'Yes, completely encrusted. Note patient was incompliant with F/U for 4 monthes'
 'Yes, leaking and mucous drainage' 'Yes, infection'
 'Yes, urethrocutaneous fistula' 'Yes (Fell out)' 'Yes (Occluded)'
 'yes - some clots' 'N/a' 'yes - required irrigation' 'Yes' 'yes'
 'fell out' 'n' 1]

In [622]:
def clean_spcomp(val):
    if pd.isna(val):
        return np.nan
    v = str(val).strip().lower()
    # Handle "no" values
    if v in ['no', 'n', '0', 'n/a']:
        return 0
    # Handle "yes" values, or if the text contains "yes"
    if v.startswith('yes') or v == '1' or 'yes' in v:
        return 1
    # If it’s just "fell out" or other text, count as complication (1)
    if 'fell out' in v or 'infection' in v or 'fistula' in v or 'drainage' in v or 'occluded' in v or 'clots' in v or 'irrigation' in v or 'encrusted' in v:
        return 1
    # Anything else, set as nan
    return np.nan

df["spcomplication_clean"] = df["spcomplication"].apply(clean_spcomp)

In [623]:
print(df["spcomplication_clean"].unique())

[0 1]

In [624]:
df = df.drop("spcomplication", axis=1)

In [625]:
print(df.columns[df.isna().any()])

Index(['dob(yyyy-mm-dd)', 'erectilepre', 'tissue', 'cathdays', 'patent',
       'erectilepost', 'stricture', 'strictureintervention', 'age_calc'],
      dtype='object')

Cleaning satisfaction column

Cleaning erectile column

In [626]:
import numpy as np

def clean_erectilepre(val):
    if pd.isna(val):
        return np.nan
    v = str(val).lower().strip()
    # 1. Gender reassignment gets 0
    if 'gender reassignment' in v:
        return 0
    # 2. Obvious yes answers (any variant of "yes")
    if v.startswith('yes') or v.startswith('y;') or v == '1' or 'yes' in v:
        return 1
    # 3. Obvious no answers
    if v.startswith('no') or v == '0' or 'no' in v or 'not sexually active' in v:
        return 0
    # 4. Not sexually active or unclear? Make missing for now.
    if '?' in v or 'probably' in v or 'no records' in v:
        return np.nan
    # 5. If it contains a number in the yes (e.g., yes (5/10)), treat as 1
    if '/' in v and 'yes' in v:
        return 1
    # 6. Default to nan if not caught above
    return np.nan

df["erectilepre_clean"] = df["erectilepre"].apply(clean_erectilepre)

In [627]:
print(df["erectilepre_clean"].unique())

[ 1.  0. nan]

In [628]:
mask = df["erectilepre_clean"].isna()
unknown_rows = df[mask]
print(unknown_rows[["erectilepre_clean", "failure"]])

      erectilepre_clean  failure
8                   NaN        1
85                  NaN        0
86                  NaN        1
94                  NaN        0
98                  NaN        0
239                 NaN        0
347                 NaN        0
708                 NaN        0
722                 NaN        0
726                 NaN        0
883                 NaN        0
1159                NaN        1

In [629]:
print(unknown_rows["failure"].value_counts())

failure
0    9
1    3
Name: count, dtype: int64

In [630]:
mode_val = df["erectilepre_clean"].mode()[0]
df["erectilepre_clean"] = df["erectilepre_clean"].fillna(mode_val)

In [631]:
print(df["erectilepre_clean"].unique())

[1. 0.]

In [632]:
print(df["dob(yyyy-mm-dd)"].isna().sum())

15

In [633]:
mask = df["dob(yyyy-mm-dd)"].isna()
unknown_rows = df[mask]
print(unknown_rows[["dob(yyyy-mm-dd)", "failure"]])

    dob(yyyy-mm-dd)  failure
76              NaT        1
88              NaT        0
89              NaT        1
98              NaT        0
385             NaT        0
387             NaT        0
390             NaT        0
391             NaT        0
395             NaT        1
396             NaT        0
397             NaT        0
398             NaT        0
400             NaT        0
758             NaT        0
818             NaT        0

In [634]:
df = df.drop(columns=["dob(yyyy-mm-dd)"])

In [635]:
df = df.drop(columns=["erectilepre"])

In [636]:
print(df.columns[df.isna().any()])

Index(['tissue', 'cathdays', 'patent', 'erectilepost', 'stricture',
       'strictureintervention', 'age_calc'],
      dtype='object')

In [637]:
df["tissue"] = df["tissue"].replace({'1 (penobulbar only; not proximal bulbar)': 1})

/var/folders/cl/h60hyp6s1jg6rr9n0nfgvphw0000gn/T/ipykernel_4194/2050400628.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["tissue"] = df["tissue"].replace({'1 (penobulbar only; not proximal bulbar)': 1})

In [638]:
print(df["tissue"].unique())

[ 1.  0.  2.  4.  3.  5. nan]

In [639]:
mask = df["tissue"].isna()
unknown_rows = df[mask]
print(unknown_rows[["tissue", "failure"]])

      tissue  failure
1445     NaN        0

In [640]:
df = df.dropna(subset=['tissue'])

In [641]:
print(df["tissue"].unique())

[1. 0. 2. 4. 3. 5.]

In [642]:
#Hot encodinh for the tissue column
#Tissue Transfer 0=no, 1=yes BMG, 2= yes tunica dartos(vaginalis) flap, 3=yes combined graft/flap, 4= PIF, 5= other
tissue_dummies = pd.get_dummies(df["tissue"], prefix="tissue", dummy_na=True)
df = pd.concat([df, tissue_dummies], axis=1)

In [643]:
df = df.drop(columns=["tissue"])

In [644]:
print(df.columns[df.isna().any()])

Index(['cathdays', 'patent', 'erectilepost', 'stricture',
       'strictureintervention', 'age_calc'],
      dtype='object')

Cleaning the cathdays column

In [645]:
print(df["cathdays"].unique())

[28 5 27 21 29 22 nan 25 12 24 23 31 6 33 32 30 36 14 20 26 16 7 18 17 38
 '?' '18 months (SPC)' 120 '26 (SPC)' '21 (SPC)' 40
 datetime.datetime(1900, 1, 21, 0, 0) 19 35 4 'Still in' 'No record'
 '37 (SPC)' 39 '28 (SPC)' 15 34 '49~' 37 '21?' 102 'Not recorded' 50 13 53
 49 43
 '? - no communication from his local specialist in cranbrooke, who presumably removed catheter'
 45 'No records' 11 57 44 '29 (unclear when cath removed)'
 'FU- 3-4 wks with other doc' 'follow-up not in chart'
 'follw up not in chart (~4 weeks)' 'follow-up not in chart (~3 weeks)'
 '~3 weeks in Winnipeg ' '31 (foley); ??? (suprapubic) '
 '?? (stent + SPC)' 'unknown' 'no FU (said 3 weeks)' 'no FU' 'unclear'
 'no record' 'no records' '22 (foley out, SPC still in)' 9 79
 'not removed yet'
 'no record (complications before catheter removal and ended up keeping catheter longer than expected. Unfortunately Mr. Sandnes ulimately passed away. No record if catheter was removed prior to his passing)'
 52 48 -44501]

In [646]:
mask = df["cathdays"].isin(['no record (complications before catheter removal and ended up keeping catheter longer than expected. Unfortunately Mr. Sandnes ulimately passed away. No record if catheter was removed prior to his passing)'])
unknown_rows = df[mask]
print(unknown_rows[["cathdays", "failure"]])

                                               cathdays  failure
1412  no record (complications before catheter remov...        0

In [647]:
df = df[~mask]

In [648]:
def clean_cathdays(val):
    # Handle missing/empty
    if pd.isna(val):
        return np.nan
    s = str(val).lower().strip()
    # If contains "no record", "not recorded", "unclear", etc., return NaN
    if ('no record' in s or 'not recorded' in s or 'unclear' in s or 
        'still in' in s or 'not removed' in s or '?' in s or
        'follw up not in chart' in s or 'follow-up not in chart' in s or
        'unknown' in s):
        return np.nan
    # Try to extract the first number found (including negatives, e.g., -44501)
    nums = re.findall(r'-?\d+', s)
    if nums:
        return float(nums[0])
    return np.nan

df['cathdays_clean'] = df['cathdays'].apply(clean_cathdays)

In [649]:
print(df["cathdays_clean"].unique())

[ 2.8000e+01  5.0000e+00  2.7000e+01  2.1000e+01  2.9000e+01  2.2000e+01
         nan  2.5000e+01  1.2000e+01  2.4000e+01  2.3000e+01  3.1000e+01
  6.0000e+00  3.3000e+01  3.2000e+01  3.0000e+01  3.6000e+01  1.4000e+01
  2.0000e+01  2.6000e+01  1.6000e+01  7.0000e+00  1.8000e+01  1.7000e+01
  3.8000e+01  1.2000e+02  4.0000e+01  1.9000e+03  1.9000e+01  3.5000e+01
  4.0000e+00  3.7000e+01  3.9000e+01  1.5000e+01  3.4000e+01  4.9000e+01
  1.0200e+02  5.0000e+01  1.3000e+01  5.3000e+01  4.3000e+01  4.5000e+01
  1.1000e+01  5.7000e+01  4.4000e+01  3.0000e+00  9.0000e+00  7.9000e+01
  5.2000e+01  4.8000e+01 -4.4501e+04]

In [650]:
mask_bad_cathdays = (df['cathdays_clean'] < 0)
print(df[mask_bad_cathdays][['cathdays_clean', 'failure']])

      cathdays_clean  failure
1534        -44501.0        0

In [651]:
df = df[~mask_bad_cathdays]

In [652]:
med = df['cathdays_clean'].median()
df['cathdays_clean'] = df['cathdays_clean'].fillna(med)

In [653]:
print(df["cathdays_clean"].unique())

[  28.    5.   27.   21.   29.   22.   25.   12.   24.   23.   31.    6.
   33.   32.   30.   36.   14.   20.   26.   16.    7.   18.   17.   38.
  120.   40. 1900.   19.   35.    4.   37.   39.   15.   34.   49.  102.
   50.   13.   53.   43.   45.   11.   57.   44.    3.    9.   79.   52.
   48.]

In [654]:
df = df.drop(columns=["cathdays"])

In [655]:
print(df.columns[df.isna().any()])

Index(['patent', 'erectilepost', 'stricture', 'strictureintervention',
       'age_calc'],
      dtype='object')

In [656]:
print(df["patent"].unique())

[ 1.  0. nan  2.]

In [657]:
mask_patent = df['patent'] == 2
print(df[mask_patent][['patent', 'failure']])

      patent  failure
1503     2.0        0

In [658]:
mask_p = (df['patent']).isna()
print(df[mask_p][['patent', 'failure']])

     patent  failure
246     NaN        1

In [659]:
df = df[~mask_patent]
df = df[~mask_p]

/var/folders/cl/h60hyp6s1jg6rr9n0nfgvphw0000gn/T/ipykernel_4194/445737566.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df = df[~mask_p]

In [660]:
print(df["patent"].unique())

[1. 0.]

In [661]:
print(df.columns[df.isna().any()])

Index(['erectilepost', 'stricture', 'strictureintervention', 'age_calc'], dtype='object')

In [662]:
print(df["erectilepost"].unique())

[1 0 nan 2 '?0 (gender reassign phalloplasty)' '?1 (SCI)' 3 4
 'pre-op dysfunction' '1 (no comment was made - assumed same)'
 '1 (no comments on changes but significant ED before/after)'
 '2 (comparing "satisifactory" pre-op with "significant ED" post op'
 'not mentioned' '2 ( significant ED but unclear whether worse post-op)'
 '1 (severe pre-op ED, but no comments post-op)' 'no comments on function'
 '1 responding to cialis' 'no']

In [663]:
import numpy as np

def clean_erectilepost(val):
    if pd.isna(val):
        return np.nan
    v = str(val).lower().strip()
    # Handle pure numeric codes
    if v in ['0', '1', '2', '3', '4']:
        return int(v)
    # Handle "no" (with or without text)
    if v == 'no' or v == 'no comments on function' or v == 'pre-op dysfunction':
        return 0
    # Handle special cases that contain "1"
    if v.startswith('1') or 'same' in v or 'cialis' in v or 'no comments' in v:
        return 1
    # Handle special cases that contain "2"
    if v.startswith('2') or 'worse' in v or 'significant ed' in v:
        return 2
    # Handle "3" or "ejac" for ejaculatory dysfunction
    if v.startswith('3') or 'ejac' in v:
        return 3
    # If "not mentioned" or "gender reassignment", treat as missing
    if 'not mentioned' in v or 'gender reassign' in v:
        return np.nan
    # If nothing matches, leave as NaN
    return np.nan

df["erectilepost_clean"] = df["erectilepost"].apply(clean_erectilepost)

In [664]:
print(df["erectilepost_clean"].unique())

[ 1.  0. nan  2.  3.  4.]

In [665]:
mask_e = (df['erectilepost_clean']).isna()
print(df[mask_e][['erectilepost_clean', 'failure']])

      erectilepost_clean  failure
6                    NaN        0
41                   NaN        0
42                   NaN        1
50                   NaN        1
57                   NaN        0
61                   NaN        0
64                   NaN        0
70                   NaN        0
72                   NaN        0
74                   NaN        0
80                   NaN        0
142                  NaN        1
159                  NaN        0
672                  NaN        0
740                  NaN        0
745                  NaN        0
909                  NaN        0
928                  NaN        0
1140                 NaN        0
1159                 NaN        1
1255                 NaN        0
1348                 NaN        0
1351                 NaN        0
1352                 NaN        0
1376                 NaN        0
1393                 NaN        0
1394                 NaN        0
1395                 NaN        0
1397                 NaN        0
1398                 NaN        0
1399                 NaN        0
1400                 NaN        0
1401                 NaN        0
1402                 NaN        0
1405                 NaN        0
1595                 NaN        0

In [666]:
print(df["erectilepost_clean"].value_counts())

erectilepost_clean
0.0    1176
1.0     150
2.0      90
3.0      12
4.0       2
Name: count, dtype: int64

In [667]:
mode_val = df["erectilepost_clean"].mode()[0]
df["erectilepost_clean"] = df["erectilepost_clean"].fillna(mode_val)

In [668]:
df = df.drop(columns = ["erectilepost"])

In [669]:
print(df.columns[df.isna().any()])

Index(['stricture', 'strictureintervention', 'age_calc'], dtype='object')

In [670]:
mask_age = (df['age_calc']).isna()
print(df[mask_age][['age_calc', 'failure']])

     age_calc  failure
76        NaN        1
88        NaN        0
89        NaN        1
98        NaN        0
385       NaN        0
387       NaN        0
390       NaN        0
391       NaN        0
395       NaN        1
396       NaN        0
397       NaN        0
398       NaN        0
400       NaN        0
758       NaN        0
818       NaN        0

In [671]:
med_age = df["age_calc"].median()
df["age_calc"] = df["age_calc"].fillna(med_age)

In [672]:
mask_stricture = (df['stricture']).isna()
print(df[mask_stricture][['stricture', 'failure']])

      stricture  failure
541         NaN        0
553         NaN        0
756         NaN        0
826         NaN        0
856         NaN        1
...         ...      ...
1400        NaN        0
1401        NaN        0
1404        NaN        0
1405        NaN        0
1595        NaN        0

[90 rows x 2 columns]

In [673]:
print(df["stricture"].value_counts())

stricture
0.0    1271
1.0     105
Name: count, dtype: int64

In [674]:
df["stricture"] = df["stricture"].fillna(0)

In [675]:
print(df["stricture"].unique())

[1. 0.]

In [676]:
df = df.drop(columns=['strictureintervention'])

In [677]:
df.columns

Index(['dateofsurgery', 'monthsurg', 'age:<50=0;>=50=1', 'stxlocation',
       'distal', 'penile', '#strictures', 'charlsons', 'cormorbidity',
       'diabetes', 'copd', 'smoker', 'bmi35+', 'prevprocedure',
       '#prevprocedures', 'cysto', 'ordate', 'urine', 'abx', 'uti',
       'los(days)', 'spc', 'transection', 'urethroplasty', 'failure', 'patent',
       'fu', 'datetofailureorfollowup', 'clavianii+', 'claviangrade',
       'earlycomps', 'pain', 'utipost', 'utirecurring', 'stricture',
       'age_calc', 'open_clean', 'stxlength_1', 'stxlength_2', 'stxetiology_0',
       'stxetiology_1', 'stxetiology_2', 'stxetiology_3', 'stxetiology_4',
       'stxetiology_5', 'stxetiology_6', 'stxlocation_clean', 'stxlocation_0',
       'stxlocation_1', 'stxlocation_2', 'stxlocation_3', 'stxlocation_4',
       'stxlocation_5', 'time_to_event', 'spcomplication_clean',
       'erectilepre_clean', 'tissue_0.0', 'tissue_1.0', 'tissue_2.0',
       'tissue_3.0', 'tissue_4.0', 'tissue_5.0', 'tissue_nan',
       'cathdays_clean', 'erectilepost_clean'],
      dtype='object')

In [678]:
print(df.columns[df.isna().any()])

Index([], dtype='object')

In [679]:
df.head()

,dateofsurgery,monthsurg,age:<50=0;>=50=1,stxlocation,distal,penile,#strictures,charlsons,cormorbidity,diabetes,...,erectilepre_clean,tissue_0.0,tissue_1.0,tissue_2.0,tissue_3.0,tissue_4.0,tissue_5.0,tissue_nan,cathdays_clean,erectilepost_clean
0,2003-08-05,258.0,1,0,0,1.0,1,0,1.0,1,...,1.0,False,True,False,False,False,False,False,28.0,1.0
1,2003-08-06,258.0,0,0,0,1.0,1,0,0.0,0,...,0.0,False,True,False,False,False,False,False,5.0,0.0
2,2003-08-21,258.0,1,2,0,0.0,1,0,0.0,0,...,0.0,True,False,False,False,False,False,False,27.0,1.0
3,2003-08-28,257.0,1,0,0,1.0,1,0,0.0,0,...,0.0,False,True,False,False,False,False,False,5.0,0.0
5,2003-09-29,256.0,0,1,0,0.0,1,0,0.0,0,...,0.0,True,False,False,False,False,False,False,21.0,0.0

In [680]:
print("After cleaning:")
print(df['failure'].value_counts())

After cleaning:
failure
0    1324
1     142
Name: count, dtype: int64

In [681]:
df = df.drop(columns=['age:<50=0;>=50=1'])

In [682]:
print(df.select_dtypes(include='object').columns)

Index(['stxlocation', 'ordate', 'urine', 'los(days)', 'earlycomps',
       'stxlocation_clean'],
      dtype='object')

In [683]:
print(df["stxlocation_clean"].head(20))

0     [0]
1     [0]
2     [2]
3     [0]
5     [1]
6     [1]
7     [1]
8     [1]
9     [1]
10    [0]
11    [1]
12    [1]
13    [1]
14    [1]
15    [1]
16    [2]
17    [1]
18    [1]
19    [1]
20    [3]
Name: stxlocation_clean, dtype: object

In [684]:
df.columns

Index(['dateofsurgery', 'monthsurg', 'stxlocation', 'distal', 'penile',
       '#strictures', 'charlsons', 'cormorbidity', 'diabetes', 'copd',
       'smoker', 'bmi35+', 'prevprocedure', '#prevprocedures', 'cysto',
       'ordate', 'urine', 'abx', 'uti', 'los(days)', 'spc', 'transection',
       'urethroplasty', 'failure', 'patent', 'fu', 'datetofailureorfollowup',
       'clavianii+', 'claviangrade', 'earlycomps', 'pain', 'utipost',
       'utirecurring', 'stricture', 'age_calc', 'open_clean', 'stxlength_1',
       'stxlength_2', 'stxetiology_0', 'stxetiology_1', 'stxetiology_2',
       'stxetiology_3', 'stxetiology_4', 'stxetiology_5', 'stxetiology_6',
       'stxlocation_clean', 'stxlocation_0', 'stxlocation_1', 'stxlocation_2',
       'stxlocation_3', 'stxlocation_4', 'stxlocation_5', 'time_to_event',
       'spcomplication_clean', 'erectilepre_clean', 'tissue_0.0', 'tissue_1.0',
       'tissue_2.0', 'tissue_3.0', 'tissue_4.0', 'tissue_5.0', 'tissue_nan',
       'cathdays_clean', 'erectilepost_clean'],
      dtype='object')

In [685]:
df = df.drop(columns=['stxlocation_clean'])

In [686]:
df = df.drop(columns=['stxlocation'])

In [687]:
print(df["earlycomps"].head(20))
print(df["earlycomps"].unique())

df["earlycomps"] = df["earlycomps"].replace({"No":0})

0     0
1     0
2     0
3     0
5     0
6     1
7     0
8     0
9     0
10    1
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
Name: earlycomps, dtype: object
[0 1 'No' 2]

/var/folders/cl/h60hyp6s1jg6rr9n0nfgvphw0000gn/T/ipykernel_4194/3026888170.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["earlycomps"] = df["earlycomps"].replace({"No":0})

In [688]:
print(df["earlycomps"].unique())

[0 1 2]

In [689]:
print(df["los(days)"].unique())
print(df["los(days)"].dtype)

[2 5 4 6 3 7 31 0 18 1 11 8 10]
object

In [690]:
df["los(days)"] = pd.to_numeric(df["los(days)"], errors='coerce')

In [691]:
print(df["los(days)"].unique())
print(df["los(days)"].dtype)

[ 2  5  4  6  3  7 31  0 18  1 11  8 10]
int64

In [692]:
print(df["urine"].unique())
print(df["urine"].dtype)

[0 1 'no record' 'negative']
object

In [694]:
df["urine"] = df["urine"].replace({"negative": 0})

In [696]:
print(df['urine'].unique())
print(df['urine'].dtype)
urine_mode = df["urine"].mode()[0]
print(urine_mode)

[0 1 'no record']
object
0

In [697]:
df["urine"] = df["urine"].replace({"no record": urine_mode})

/var/folders/cl/h60hyp6s1jg6rr9n0nfgvphw0000gn/T/ipykernel_4194/3951468654.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["urine"] = df["urine"].replace({"no record": urine_mode})

In [698]:
mask_urine = (df['urine']).isin(["no record"])
print(df[mask_urine][['urine', 'failure']])

Empty DataFrame
Columns: [urine, failure]
Index: []

In [699]:
print(df['urine'].unique())
print(df['urine'].dtype)

[0 1]
int64

In [701]:
print(df['ordate'].unique())
print(df['ordate'].dtype)

[datetime.datetime(2003, 8, 5, 0, 0) datetime.datetime(2003, 8, 6, 0, 0)
 datetime.datetime(2003, 8, 21, 0, 0) datetime.datetime(2003, 8, 28, 0, 0)
 datetime.datetime(2003, 9, 29, 0, 0)
 datetime.datetime(2003, 10, 23, 0, 0)
 datetime.datetime(2003, 11, 10, 0, 0)
 datetime.datetime(2003, 11, 24, 0, 0)
 datetime.datetime(2003, 12, 8, 0, 0) datetime.datetime(2004, 1, 5, 0, 0)
 datetime.datetime(2004, 1, 16, 0, 0) datetime.datetime(2004, 1, 19, 0, 0)
 datetime.datetime(2004, 2, 2, 0, 0) datetime.datetime(2004, 2, 3, 0, 0)
 datetime.datetime(2004, 2, 4, 0, 0) datetime.datetime(2004, 2, 5, 0, 0)
 datetime.datetime(2004, 3, 1, 0, 0) datetime.datetime(2004, 3, 12, 0, 0)
 datetime.datetime(2004, 3, 15, 0, 0) datetime.datetime(2004, 3, 29, 0, 0)
 datetime.datetime(2004, 4, 12, 0, 0) datetime.datetime(2004, 4, 26, 0, 0)
 datetime.datetime(2004, 5, 3, 0, 0) datetime.datetime(2004, 5, 7, 0, 0)
 datetime.datetime(2004, 5, 10, 0, 0) datetime.datetime(2004, 6, 5, 0, 0)
 datetime.datetime(2004, 6, 7, 0, 0) datetime.datetime(2004, 6, 14, 0, 0)
 datetime.datetime(2004, 7, 12, 0, 0) datetime.datetime(2004, 8, 3, 0, 0)
 datetime.datetime(2004, 8, 5, 0, 0) datetime.datetime(2004, 8, 16, 0, 0)
 datetime.datetime(2004, 8, 26, 0, 0) datetime.datetime(2004, 9, 13, 0, 0)
 datetime.datetime(2004, 9, 24, 0, 0) datetime.datetime(2004, 9, 27, 0, 0)
 datetime.datetime(2004, 10, 4, 0, 0) datetime.datetime(2004, 11, 1, 0, 0)
 datetime.datetime(2004, 11, 15, 0, 0)
 datetime.datetime(2004, 11, 19, 0, 0)
 datetime.datetime(2004, 11, 29, 0, 0)
 datetime.datetime(2004, 12, 13, 0, 0)
 datetime.datetime(2004, 12, 17, 0, 0)
 datetime.datetime(2004, 12, 20, 0, 0)
 datetime.datetime(2005, 1, 14, 0, 0) datetime.datetime(2005, 1, 17, 0, 0)
 datetime.datetime(2005, 1, 31, 0, 0) datetime.datetime(2005, 2, 5, 0, 0)
 datetime.datetime(2005, 2, 14, 0, 0) datetime.datetime(2005, 2, 28, 0, 0)
 datetime.datetime(2005, 3, 11, 0, 0) datetime.datetime(2005, 3, 14, 0, 0)
 datetime.datetime(2005, 3, 28, 0, 0) datetime.datetime(2005, 4, 8, 0, 0)
 datetime.datetime(2005, 4, 11, 0, 0) datetime.datetime(2005, 4, 25, 0, 0)
 datetime.datetime(2005, 5, 9, 0, 0) datetime.datetime(2005, 6, 3, 0, 0)
 datetime.datetime(2005, 6, 13, 0, 0) datetime.datetime(2005, 6, 20, 0, 0)
 datetime.datetime(2005, 7, 5, 0, 0) datetime.datetime(2005, 7, 19, 0, 0)
 datetime.datetime(2005, 7, 29, 0, 0) datetime.datetime(2005, 8, 8, 0, 0)
 datetime.datetime(2005, 9, 10, 0, 0) datetime.datetime(2005, 9, 12, 0, 0)
 datetime.datetime(2005, 9, 16, 0, 0) datetime.datetime(2005, 9, 23, 0, 0)
 datetime.datetime(2005, 9, 25, 0, 0)
 datetime.datetime(2005, 10, 17, 0, 0)
 datetime.datetime(2005, 10, 21, 0, 0)
 datetime.datetime(2005, 11, 5, 0, 0) datetime.datetime(2005, 11, 7, 0, 0)
 datetime.datetime(2005, 11, 18, 0, 0)
 datetime.datetime(2005, 11, 21, 0, 0)
 datetime.datetime(2005, 12, 5, 0, 0)
 datetime.datetime(2005, 12, 16, 0, 0) datetime.datetime(2006, 1, 4, 0, 0)
 datetime.datetime(2006, 1, 10, 0, 0) datetime.datetime(2006, 1, 13, 0, 0)
 datetime.datetime(2006, 1, 16, 0, 0) datetime.datetime(2006, 1, 30, 0, 0)
 datetime.datetime(2006, 2, 10, 0, 0) datetime.datetime(2006, 2, 13, 0, 0)
 datetime.datetime(2006, 2, 27, 0, 0) datetime.datetime(2006, 3, 10, 0, 0)
 datetime.datetime(2006, 3, 13, 0, 0) datetime.datetime(2006, 3, 22, 0, 0)
 datetime.datetime(2006, 3, 27, 0, 0) datetime.datetime(2006, 4, 4, 0, 0)
 datetime.datetime(2006, 4, 7, 0, 0) datetime.datetime(2006, 4, 10, 0, 0)
 datetime.datetime(2006, 4, 24, 0, 0) datetime.datetime(2006, 5, 5, 0, 0)
 datetime.datetime(2006, 5, 8, 0, 0) datetime.datetime(2006, 5, 26, 0, 0)
 datetime.datetime(2006, 6, 2, 0, 0) datetime.datetime(2006, 6, 5, 0, 0)
 datetime.datetime(2006, 6, 12, 0, 0) datetime.datetime(2006, 7, 17, 0, 0)
 datetime.datetime(2006, 7, 31, 0, 0) datetime.datetime(2006, 8, 8, 0, 0)
 datetime.datetime(2006, 8, 11, 0, 0) datetime.datetime(2006, 8, 16, 0, 0)
 datetime.datetime(2006, 8, 28, 0, 0) datetime.datetime(2006, 9, 11, 0, 0)
 datetime.datetime(2006, 9, 25, 0, 0) datetime.datetime(2006, 10, 6, 0, 0)
 datetime.datetime(2006, 11, 3, 0, 0)
 datetime.datetime(2006, 11, 20, 0, 0) datetime.datetime(2007, 1, 6, 0, 0)
 datetime.datetime(2007, 1, 22, 0, 0) datetime.datetime(2007, 2, 6, 0, 0)
 datetime.datetime(2007, 3, 6, 0, 0) datetime.datetime(2007, 4, 6, 0, 0)
 datetime.datetime(2007, 5, 6, 0, 0) datetime.datetime(2007, 6, 6, 0, 0)
 datetime.datetime(2007, 7, 6, 0, 0) datetime.datetime(2007, 8, 6, 0, 0)
 datetime.datetime(2007, 8, 9, 0, 0) datetime.datetime(2007, 9, 6, 0, 0)
 datetime.datetime(2007, 10, 6, 0, 0) datetime.datetime(2007, 11, 6, 0, 0)
 datetime.datetime(2007, 12, 6, 0, 0)
 datetime.datetime(2007, 12, 18, 0, 0)
 datetime.datetime(2008, 1, 11, 0, 0) datetime.datetime(2008, 2, 8, 0, 0)
 datetime.datetime(2008, 3, 7, 0, 0) datetime.datetime(2008, 4, 7, 0, 0)
 datetime.datetime(2008, 5, 7, 0, 0) datetime.datetime(2008, 6, 7, 0, 0)
 datetime.datetime(2008, 7, 7, 0, 0) datetime.datetime(2008, 8, 7, 0, 0)
 datetime.datetime(2008, 9, 7, 0, 0) datetime.datetime(2008, 10, 7, 0, 0)
 datetime.datetime(2008, 11, 7, 0, 0) datetime.datetime(2008, 12, 5, 0, 0)
 datetime.datetime(2009, 1, 8, 0, 0) datetime.datetime(2009, 2, 8, 0, 0)
 datetime.datetime(2009, 3, 8, 0, 0) datetime.datetime(2009, 4, 8, 0, 0)
 datetime.datetime(2009, 5, 8, 0, 0) datetime.datetime(2009, 6, 8, 0, 0)
 datetime.datetime(2009, 7, 8, 0, 0) datetime.datetime(2009, 8, 8, 0, 0)
 datetime.datetime(2009, 9, 8, 0, 0) datetime.datetime(2009, 10, 9, 0, 0)
 datetime.datetime(2009, 10, 19, 0, 0)
 datetime.datetime(2009, 11, 9, 0, 0)
 datetime.datetime(2009, 11, 16, 0, 0)
 datetime.datetime(2009, 12, 1, 0, 0) datetime.datetime(2010, 1, 9, 0, 0)
 datetime.datetime(2010, 1, 18, 0, 0) datetime.datetime(2010, 2, 1, 0, 0)
 datetime.datetime(2010, 2, 9, 0, 0) datetime.datetime(2010, 3, 1, 0, 0)
 datetime.datetime(2010, 3, 4, 0, 0) datetime.datetime(2010, 3, 8, 0, 0)
 datetime.datetime(2010, 3, 9, 0, 0) datetime.datetime(2010, 3, 12, 0, 0)
 datetime.datetime(2010, 4, 5, 0, 0) datetime.datetime(2010, 5, 10, 0, 0)
 datetime.datetime(2010, 8, 9, 0, 0) datetime.datetime(2010, 9, 3, 0, 0)
 datetime.datetime(2010, 9, 24, 0, 0)
 datetime.datetime(2010, 11, 15, 0, 0)
 datetime.datetime(2010, 11, 19, 0, 0)
 datetime.datetime(2010, 12, 7, 0, 0) datetime.datetime(2011, 1, 17, 0, 0)
 datetime.datetime(2011, 1, 31, 0, 0) datetime.datetime(2011, 2, 7, 0, 0)
 datetime.datetime(2011, 2, 24, 0, 0) datetime.datetime(2011, 2, 25, 0, 0)
 datetime.datetime(2011, 3, 14, 0, 0) datetime.datetime(2011, 4, 18, 0, 0)
 datetime.datetime(2011, 4, 25, 0, 0) datetime.datetime(2011, 5, 2, 0, 0)
 datetime.datetime(2011, 5, 9, 0, 0) datetime.datetime(2011, 5, 19, 0, 0)
 datetime.datetime(2011, 5, 26, 0, 0) datetime.datetime(2011, 5, 30, 0, 0)
 datetime.datetime(2011, 6, 6, 0, 0) datetime.datetime(2011, 6, 9, 0, 0)
 datetime.datetime(2011, 6, 27, 0, 0) datetime.datetime(2011, 7, 7, 0, 0)
 datetime.datetime(2011, 7, 11, 0, 0) datetime.datetime(2011, 7, 15, 0, 0)
 datetime.datetime(2011, 7, 18, 0, 0) datetime.datetime(2011, 8, 8, 0, 0)
 datetime.datetime(2011, 8, 9, 0, 0) datetime.datetime(2011, 8, 29, 0, 0)
 datetime.datetime(2011, 9, 8, 0, 0) datetime.datetime(2011, 9, 12, 0, 0)
 datetime.datetime(2011, 9, 19, 0, 0) datetime.datetime(2011, 9, 26, 0, 0)
 datetime.datetime(2011, 10, 3, 0, 0)
 datetime.datetime(2011, 10, 17, 0, 0)
 datetime.datetime(2011, 10, 21, 0, 0)
 datetime.datetime(2011, 10, 24, 0, 0)
 datetime.datetime(2011, 11, 7, 0, 0)
 datetime.datetime(2011, 11, 21, 0, 0)
 datetime.datetime(2011, 11, 29, 0, 0)
 datetime.datetime(2011, 12, 5, 0, 0) datetime.datetime(2011, 12, 9, 0, 0)
 datetime.datetime(2011, 12, 12, 0, 0)
 datetime.datetime(2011, 12, 19, 0, 0) datetime.datetime(2012, 1, 9, 0, 0)
 datetime.datetime(2012, 1, 13, 0, 0) datetime.datetime(2012, 1, 16, 0, 0)
 datetime.datetime(2012, 1, 30, 0, 0) datetime.datetime(2012, 2, 6, 0, 0)
 datetime.datetime(2012, 2, 13, 0, 0) datetime.datetime(2012, 2, 16, 0, 0)
 datetime.datetime(2012, 2, 27, 0, 0) datetime.datetime(2012, 3, 5, 0, 0)
 datetime.datetime(2012, 3, 9, 0, 0) datetime.datetime(2012, 3, 12, 0, 0)
 datetime.datetime(2012, 3, 19, 0, 0) datetime.datetime(2012, 4, 9, 0, 0)
 datetime.datetime(2012, 4, 16, 0, 0) datetime.datetime(2012, 4, 23, 0, 0)
 datetime.datetime(2012, 4, 30, 0, 0) datetime.datetime(2012, 5, 3, 0, 0)
 datetime.datetime(2012, 5, 7, 0, 0) datetime.datetime(2012, 5, 14, 0, 0)
 datetime.datetime(2012, 5, 25, 0, 0) datetime.datetime(2012, 5, 28, 0, 0)
 datetime.datetime(2012, 6, 4, 0, 0) datetime.datetime(2012, 6, 11, 0, 0)
 datetime.datetime(2012, 6, 15, 0, 0) datetime.datetime(2012, 6, 20, 0, 0)
 datetime.datetime(2012, 7, 6, 0, 0) datetime.datetime(2012, 7, 9, 0, 0)
 datetime.datetime(2012, 7, 12, 0, 0) datetime.datetime(2012, 7, 18, 0, 0)
 datetime.datetime(2012, 7, 24, 0, 0) datetime.datetime(2012, 7, 30, 0, 0)
 datetime.datetime(2012, 8, 27, 0, 0) datetime.datetime(2012, 9, 17, 0, 0)
 datetime.datetime(2012, 9, 18, 0, 0) datetime.datetime(2012, 9, 24, 0, 0)
 datetime.datetime(2012, 10, 15, 0, 0)
 datetime.datetime(2012, 10, 22, 0, 0)
 datetime.datetime(2012, 10, 25, 0, 0)
 datetime.datetime(2012, 11, 5, 0, 0) datetime.datetime(2012, 11, 9, 0, 0)
 datetime.datetime(2012, 11, 19, 0, 0)
 datetime.datetime(2012, 11, 20, 0, 0)
 datetime.datetime(2012, 11, 30, 0, 0)
 datetime.datetime(2012, 12, 3, 0, 0) datetime.datetime(2012, 12, 6, 0, 0)
 datetime.datetime(2012, 12, 10, 0, 0) datetime.datetime(2013, 1, 7, 0, 0)
 datetime.datetime(2013, 1, 14, 0, 0) datetime.datetime(2013, 1, 28, 0, 0)
 datetime.datetime(2013, 2, 4, 0, 0) datetime.datetime(2013, 2, 19, 0, 0)
 datetime.datetime(2013, 2, 25, 0, 0) datetime.datetime(2013, 2, 28, 0, 0)
 datetime.datetime(2013, 3, 4, 0, 0) datetime.datetime(2013, 3, 8, 0, 0)
 datetime.datetime(2013, 3, 11, 0, 0) datetime.datetime(2013, 3, 13, 0, 0)
 datetime.datetime(2013, 3, 18, 0, 0) datetime.datetime(2013, 4, 1, 0, 0)
 datetime.datetime(2013, 4, 8, 0, 0) datetime.datetime(2013, 4, 15, 0, 0)
 datetime.datetime(2013, 4, 19, 0, 0) datetime.datetime(2013, 4, 22, 0, 0)
 datetime.datetime(2013, 4, 24, 0, 0) datetime.datetime(2013, 4, 25, 0, 0)
 datetime.datetime(2013, 4, 29, 0, 0) datetime.datetime(2013, 5, 13, 0, 0)
 datetime.datetime(2013, 5, 27, 0, 0) datetime.datetime(2013, 5, 31, 0, 0)
 datetime.datetime(2013, 6, 3, 0, 0) datetime.datetime(2013, 6, 7, 0, 0)
 datetime.datetime(2013, 6, 10, 0, 0) datetime.datetime(2013, 6, 17, 0, 0)
 datetime.datetime(2013, 7, 5, 0, 0) datetime.datetime(2013, 7, 9, 0, 0)
 datetime.datetime(2013, 8, 7, 0, 0) datetime.datetime(2013, 8, 9, 0, 0)
 datetime.datetime(2013, 8, 12, 0, 0) datetime.datetime(2013, 8, 13, 0, 0)
 datetime.datetime(2013, 8, 16, 0, 0) datetime.datetime(2013, 8, 19, 0, 0)
 datetime.datetime(2013, 8, 26, 0, 0) datetime.datetime(2013, 8, 30, 0, 0)
 datetime.datetime(2013, 9, 16, 0, 0) datetime.datetime(2013, 9, 23, 0, 0)
 datetime.datetime(2013, 9, 30, 0, 0) datetime.datetime(2013, 10, 7, 0, 0)
 datetime.datetime(2013, 10, 17, 0, 0)
 datetime.datetime(2013, 10, 18, 0, 0)
 datetime.datetime(2013, 10, 25, 0, 0)
 datetime.datetime(2013, 11, 4, 0, 0) datetime.datetime(2013, 11, 6, 0, 0)
 datetime.datetime(2013, 11, 7, 0, 0)
 datetime.datetime(2013, 11, 18, 0, 0)
 datetime.datetime(2013, 11, 22, 0, 0)
 datetime.datetime(2013, 11, 25, 0, 0)
 datetime.datetime(2013, 12, 4, 0, 0) datetime.datetime(2013, 12, 9, 0, 0)
 datetime.datetime(2014, 1, 6, 0, 0) datetime.datetime(2014, 1, 13, 0, 0)
 datetime.datetime(2014, 1, 15, 0, 0) datetime.datetime(2014, 1, 20, 0, 0)
 datetime.datetime(2014, 1, 27, 0, 0) datetime.datetime(2014, 2, 3, 0, 0)
 datetime.datetime(2014, 2, 10, 0, 0) datetime.datetime(2014, 2, 12, 0, 0)
 datetime.datetime(2014, 2, 24, 0, 0) datetime.datetime(2014, 3, 3, 0, 0)
 datetime.datetime(2014, 3, 10, 0, 0) datetime.datetime(2014, 3, 11, 0, 0)
 datetime.datetime(2014, 3, 12, 0, 0) datetime.datetime(2014, 3, 17, 0, 0)
 datetime.datetime(2014, 3, 31, 0, 0) datetime.datetime(2014, 4, 7, 0, 0)
 datetime.datetime(2014, 4, 14, 0, 0) datetime.datetime(2014, 4, 20, 0, 0)
 datetime.datetime(2014, 4, 21, 0, 0) datetime.datetime(2014, 5, 2, 0, 0)
 datetime.datetime(2014, 5, 5, 0, 0) datetime.datetime(2014, 5, 12, 0, 0)
 datetime.datetime(2014, 5, 13, 0, 0) datetime.datetime(2014, 5, 23, 0, 0)
 datetime.datetime(2014, 5, 26, 0, 0) datetime.datetime(2014, 6, 2, 0, 0)
 datetime.datetime(2014, 6, 9, 0, 0) datetime.datetime(2014, 6, 23, 0, 0)
 datetime.datetime(2014, 7, 14, 0, 0) datetime.datetime(2014, 7, 16, 0, 0)
 datetime.datetime(2014, 7, 21, 0, 0) datetime.datetime(2014, 7, 28, 0, 0)
 datetime.datetime(2014, 8, 7, 0, 0) datetime.datetime(2014, 8, 11, 0, 0)
 datetime.datetime(2014, 8, 13, 0, 0) datetime.datetime(2014, 8, 18, 0, 0)
 datetime.datetime(2014, 9, 8, 0, 0) datetime.datetime(2014, 9, 15, 0, 0)
 datetime.datetime(2014, 9, 23, 0, 0) datetime.datetime(2014, 9, 29, 0, 0)
 datetime.datetime(2014, 9, 30, 0, 0) datetime.datetime(2014, 10, 6, 0, 0)
 datetime.datetime(2014, 10, 27, 0, 0)
 datetime.datetime(2014, 10, 28, 0, 0)
 datetime.datetime(2014, 11, 3, 0, 0)
 datetime.datetime(2014, 11, 17, 0, 0)
 datetime.datetime(2014, 11, 21, 0, 0)
 datetime.datetime(2014, 11, 24, 0, 0)
 datetime.datetime(2014, 12, 1, 0, 0) datetime.datetime(2014, 12, 8, 0, 0)
 datetime.datetime(2014, 12, 15, 0, 0)
 datetime.datetime(2014, 12, 29, 0, 0) datetime.datetime(2015, 1, 5, 0, 0)
 datetime.datetime(2015, 1, 12, 0, 0) datetime.datetime(2015, 1, 19, 0, 0)
 datetime.datetime(2015, 1, 26, 0, 0) datetime.datetime(2015, 2, 2, 0, 0)
 datetime.datetime(2015, 2, 6, 0, 0) datetime.datetime(2015, 2, 9, 0, 0)
 datetime.datetime(2015, 2, 12, 0, 0) datetime.datetime(2015, 2, 23, 0, 0)
 datetime.datetime(2015, 2, 25, 0, 0) datetime.datetime(2015, 3, 2, 0, 0)
 datetime.datetime(2015, 3, 9, 0, 0) datetime.datetime(2015, 3, 14, 0, 0)
 datetime.datetime(2015, 3, 16, 0, 0) datetime.datetime(2015, 4, 6, 0, 0)
 datetime.datetime(2015, 4, 13, 0, 0) datetime.datetime(2015, 4, 20, 0, 0)
 datetime.datetime(2015, 4, 24, 0, 0) datetime.datetime(2015, 4, 27, 0, 0)
 datetime.datetime(2015, 5, 4, 0, 0) datetime.datetime(2015, 5, 11, 0, 0)
 datetime.datetime(2015, 5, 15, 0, 0) datetime.datetime(2015, 5, 29, 0, 0)
 datetime.datetime(2015, 6, 1, 0, 0) datetime.datetime(2015, 6, 3, 0, 0)
 datetime.datetime(2015, 6, 8, 0, 0) datetime.datetime(2015, 6, 12, 0, 0)
 datetime.datetime(2015, 6, 15, 0, 0) datetime.datetime(2015, 6, 22, 0, 0)
 datetime.datetime(2015, 7, 13, 0, 0) datetime.datetime(2015, 7, 16, 0, 0)
 datetime.datetime(2015, 7, 20, 0, 0) datetime.datetime(2015, 7, 27, 0, 0)
 datetime.datetime(2015, 7, 28, 0, 0) datetime.datetime(2015, 8, 5, 0, 0)
 datetime.datetime(2015, 8, 14, 0, 0) datetime.datetime(2015, 8, 20, 0, 0)
 datetime.datetime(2015, 8, 31, 0, 0) datetime.datetime(2015, 9, 9, 0, 0)
 datetime.datetime(2015, 9, 14, 0, 0) datetime.datetime(2015, 9, 18, 0, 0)
 datetime.datetime(2015, 9, 21, 0, 0) datetime.datetime(2015, 9, 22, 0, 0)
 datetime.datetime(2015, 9, 25, 0, 0) datetime.datetime(2015, 9, 28, 0, 0)
 datetime.datetime(2015, 10, 5, 0, 0)
 datetime.datetime(2015, 10, 19, 0, 0)
 datetime.datetime(2015, 10, 27, 0, 0)
 datetime.datetime(2015, 11, 16, 0, 0)
 datetime.datetime(2015, 11, 23, 0, 0)
 datetime.datetime(2015, 11, 30, 0, 0)
 datetime.datetime(2015, 12, 7, 0, 0)
 datetime.datetime(2015, 12, 14, 0, 0) datetime.datetime(2016, 1, 4, 0, 0)
 datetime.datetime(2016, 1, 5, 0, 0) datetime.datetime(2016, 1, 11, 0, 0)
 datetime.datetime(2016, 1, 18, 0, 0) datetime.datetime(2016, 1, 20, 0, 0)
 datetime.datetime(2016, 1, 23, 0, 0) datetime.datetime(2016, 1, 25, 0, 0)
 datetime.datetime(2016, 1, 27, 0, 0) datetime.datetime(2016, 2, 1, 0, 0)
 datetime.datetime(2016, 2, 6, 0, 0) datetime.datetime(2016, 2, 7, 0, 0)
 datetime.datetime(2016, 2, 8, 0, 0) datetime.datetime(2016, 2, 22, 0, 0)
 datetime.datetime(2016, 2, 29, 0, 0) datetime.datetime(2016, 3, 7, 0, 0)
 datetime.datetime(2016, 3, 8, 0, 0) datetime.datetime(2016, 3, 14, 0, 0)
 datetime.datetime(2016, 3, 21, 0, 0) datetime.datetime(2016, 4, 1, 0, 0)
 datetime.datetime(2016, 4, 4, 0, 0) datetime.datetime(2016, 4, 11, 0, 0)
 datetime.datetime(2016, 4, 18, 0, 0) datetime.datetime(2016, 4, 25, 0, 0)
 datetime.datetime(2016, 4, 29, 0, 0) datetime.datetime(2016, 5, 1, 0, 0)
 datetime.datetime(2016, 5, 2, 0, 0) datetime.datetime(2016, 5, 10, 0, 0)
 datetime.datetime(2016, 5, 16, 0, 0) datetime.datetime(2016, 5, 30, 0, 0)
 datetime.datetime(2016, 6, 6, 0, 0) datetime.datetime(2016, 6, 10, 0, 0)
 datetime.datetime(2016, 6, 13, 0, 0) datetime.datetime(2016, 6, 20, 0, 0)
 datetime.datetime(2016, 7, 4, 0, 0) datetime.datetime(2016, 7, 11, 0, 0)
 datetime.datetime(2016, 7, 14, 0, 0) datetime.datetime(2016, 7, 15, 0, 0)
 datetime.datetime(2016, 7, 18, 0, 0) datetime.datetime(2016, 8, 8, 0, 0)
 datetime.datetime(2016, 8, 12, 0, 0) datetime.datetime(2016, 8, 15, 0, 0)
 datetime.datetime(2016, 8, 17, 0, 0) datetime.datetime(2016, 8, 22, 0, 0)
 datetime.datetime(2016, 9, 2, 0, 0) datetime.datetime(2016, 9, 12, 0, 0)
 datetime.datetime(2016, 9, 19, 0, 0) datetime.datetime(2016, 9, 26, 0, 0)
 datetime.datetime(2016, 9, 27, 0, 0) datetime.datetime(2016, 10, 3, 0, 0)
 datetime.datetime(2016, 10, 7, 0, 0)
 datetime.datetime(2016, 10, 15, 0, 0)
 datetime.datetime(2016, 10, 17, 0, 0)
 datetime.datetime(2016, 10, 19, 0, 0)
 datetime.datetime(2016, 10, 21, 0, 0)
 datetime.datetime(2016, 10, 31, 0, 0)
 datetime.datetime(2016, 11, 4, 0, 0) datetime.datetime(2016, 11, 7, 0, 0)
 datetime.datetime(2016, 11, 21, 0, 0)
 datetime.datetime(2016, 11, 25, 0, 0)
 datetime.datetime(2016, 11, 28, 0, 0)
 datetime.datetime(2016, 11, 30, 0, 0)
 datetime.datetime(2016, 12, 5, 0, 0) datetime.datetime(2016, 12, 8, 0, 0)
 datetime.datetime(2016, 12, 12, 0, 0)
 datetime.datetime(2016, 12, 16, 0, 0) datetime.datetime(2017, 1, 9, 0, 0)
 datetime.datetime(2017, 1, 12, 0, 0) datetime.datetime(2017, 1, 16, 0, 0)
 datetime.datetime(2017, 1, 19, 0, 0) datetime.datetime(2017, 2, 6, 0, 0)
 datetime.datetime(2017, 2, 7, 0, 0) datetime.datetime(2017, 2, 10, 0, 0)
 datetime.datetime(2017, 2, 13, 0, 0) datetime.datetime(2017, 2, 21, 0, 0)
 datetime.datetime(2017, 2, 27, 0, 0) datetime.datetime(2017, 2, 28, 0, 0)
 datetime.datetime(2017, 3, 6, 0, 0) datetime.datetime(2017, 3, 10, 0, 0)
 datetime.datetime(2017, 3, 13, 0, 0) datetime.datetime(2017, 3, 17, 0, 0)
 datetime.datetime(2017, 3, 31, 0, 0) datetime.datetime(2017, 4, 3, 0, 0)
 datetime.datetime(2017, 4, 10, 0, 0) datetime.datetime(2017, 4, 13, 0, 0)
 datetime.datetime(2017, 4, 17, 0, 0) datetime.datetime(2017, 4, 24, 0, 0)
 datetime.datetime(2017, 5, 1, 0, 0) datetime.datetime(2017, 5, 2, 0, 0)
 datetime.datetime(2017, 5, 5, 0, 0) datetime.datetime(2017, 5, 8, 0, 0)
 datetime.datetime(2017, 5, 29, 0, 0) datetime.datetime(2017, 6, 5, 0, 0)
 datetime.datetime(2017, 6, 8, 0, 0) datetime.datetime(2017, 6, 9, 0, 0)
 datetime.datetime(2017, 6, 12, 0, 0) datetime.datetime(2017, 6, 19, 0, 0)
 datetime.datetime(2017, 7, 5, 0, 0) datetime.datetime(2017, 7, 10, 0, 0)
 datetime.datetime(2017, 7, 31, 0, 0) datetime.datetime(2017, 8, 4, 0, 0)
 datetime.datetime(2017, 8, 14, 0, 0) datetime.datetime(2017, 8, 16, 0, 0)
 datetime.datetime(2017, 8, 18, 0, 0) datetime.datetime(2017, 8, 22, 0, 0)
 datetime.datetime(2017, 8, 23, 0, 0) datetime.datetime(2017, 8, 28, 0, 0)
 datetime.datetime(2017, 9, 5, 0, 0) datetime.datetime(2017, 9, 11, 0, 0)
 datetime.datetime(2017, 9, 18, 0, 0) datetime.datetime(2017, 9, 25, 0, 0)
 datetime.datetime(2017, 9, 26, 0, 0) datetime.datetime(2017, 10, 2, 0, 0)
 datetime.datetime(2017, 10, 16, 0, 0)
 datetime.datetime(2017, 10, 20, 0, 0)
 datetime.datetime(2017, 10, 23, 0, 0)
 datetime.datetime(2017, 10, 24, 0, 0)
 datetime.datetime(2017, 10, 25, 0, 0)
 datetime.datetime(2017, 10, 30, 0, 0)
 datetime.datetime(2017, 11, 1, 0, 0) datetime.datetime(2017, 11, 6, 0, 0)
 datetime.datetime(2017, 11, 7, 0, 0)
 datetime.datetime(2017, 11, 20, 0, 0)
 datetime.datetime(2017, 11, 24, 0, 0)
 datetime.datetime(2017, 11, 27, 0, 0)
 datetime.datetime(2017, 12, 5, 0, 0)

In [702]:
print(df.select_dtypes(include='object').columns)

Index(['ordate'], dtype='object')

In [706]:
df.shape

(1466, 62)

In [703]:
#Save as a csv
df.to_csv("full_cleaned.csv", index=False)

In [680]:
print(df['failure'].value_counts())

failure
0    33
1     6
Name: count, dtype: int64

In [682]:
df.shape

(39, 87)

DONT GO HERE LOL

In [74]:
#Making the subsets
x_before = df[before_surgery]
x_imm_bf = df[imm_bf_surgery]
x_imm_af = df[imm_aft_surgery]
x_post = df[post_surgery]

In [75]:
outcomes = df[outcome_vars]

x_before_with_outcomes = x_before.join(outcomes)
x_imm_bf = x_imm_bf.join(outcomes)
x_imm_af = x_imm_af.join(outcomes)
x_post = x_post.join(outcomes)

In [76]:
x_before_with_outcomes.columns

Index(['stxlocation', 'distal', 'penile', 'stxetiology', 'stxlength',
       '#strictures', 'charlsons', 'cormorbidity', 'diabetes', 'copd',
       'smoker', 'bmi35+', 'bmiexact', 'prevprocedure', '#prevprocedures',
       'cysto', 'open', 'ordate', 'urine', 'failure', 'patent',
       'satisfaction'],
      dtype='object')

In [ ]:

#x_imm_bf.columns
x_imm_af.columns
#x_post.columns

Index(['los(days)', 'spc', 'tissue', 'transection', 'urethroplasty',
       'cathremoval', 'cathdays', 'failure', 'patent', 'satisfaction'],
      dtype='object')

In [80]:
x_post.head()

,fu,failuredate,datetofailureorfollowup,complication,clavianii+,claviangrade,earlycomps,signifcomp,minorcomp,ervisits,...,utipost,utirecurring,luts,persistingluts,incontinence,stricture,strictureintervention,failure,patent,satisfaction
0,2017-09-08 00:00:00,NaN,49.0,1,0.0,0.0,0,0,4,yes,...,0,0,0,no,0,1.0,yes (DVIU every 1-2 years),0,1.0,NaN
1,2010-08-12 00:00:00,NaN,212.0,0,0.0,0.0,0,NaN,NaN,No,...,0,0,0,no,0,0.0,no,0,1.0,yes
2,NaN,NaN,212.0,0,0.0,0.0,0,NaN,NaN,no,...,0,0,0,no,0,0.0,no,0,1.0,yes
3,2015-05-19 00:00:00,2015-05-19 00:00:00,60.0,0,0.0,0.0,0,NaN,NaN,no,...,1,0,0,no,0,0.0,no,1,1.0,yes
4,NaN,NaN,212.0,1,1.0,4.0,2,7,4,yes,...,0,0,0,no,0,0.0,no,0,1.0,Not patient died approx 1.5 years post op from...

In [82]:
#save the subsets
x_before_with_outcomes.to_csv('x_before_with_outcomes.csv')
x_imm_bf.to_csv('x_imm_bf_columns.csv')
x_imm_af.to_csv('x_imm_af_columns.csv')
x_post.to_csv('x_post_columns.csv')
#x_post.columns